
[[buildings]]
name = "Headquarters"
size = [2, 2]
priority = 0

[buildings.placement]
on_water = false
on_mineral = true

[[buildings.actions]]
name = "Turn Crank"
cooldown = 1

[[buildings.actions.products]]
resource = "Watt"
value = 1

[[buildings.actions]]
name = "Print Credit"
cooldown = 1

[[buildings.actions.products]]
resource = "Credit"
value = 1

[[buildings.actions.costs]]
resource = "Watt"
value = -1

