version: '3.1'

services:
  db:
    network_mode: "host"
    image: postgres
    restart: always
    expose:
      - "5435"
    ports:
      - "5435:5435"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    command: -p 5435
  db-test:
    network_mode: "host"
    image: postgres
    restart: always
    expose:
      - "5433"
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    command: -p 5433
