
[[buildings]]
name = "Headquarters"
size = [2, 2]
priority = 0

[buildings.placement]
on_water = false
on_mineral = true

[[buildings.ticked]]
every_n_ticks = 1

[[buildings.ticked.products]]
resource = "Credit"
value = 1

[[buildings.actions]]
name = "Increase Cash Flow"
cooldown = 2

[[buildings.actions.costs]]
resource = "Credit"
value = 1

[[buildings.actions.products]]
resource = "Credit"
value = 2
